// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8JVQFv0JCaarKX_kmiY5iZhL85mevj4E',
    appId: '1:375576181839:web:9a6899966cf816a929be3a',
    messagingSenderId: '375576181839',
    projectId: 'habittracker-443a8',
    authDomain: 'habittracker-443a8.firebaseapp.com',
    storageBucket: 'habittracker-443a8.firebasestorage.app',
    measurementId: 'G-BZ80F8V67G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmfn9uECid-tzUhmnLbht1rc0Tp3Efq8w',
    appId: '1:375576181839:android:f7d13a6538d13aaf29be3a',
    messagingSenderId: '375576181839',
    projectId: 'habittracker-443a8',
    storageBucket: 'habittracker-443a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgmYwVgTZMtsJDeSxdRbBwSkcdRusix8U',
    appId: '1:375576181839:ios:9431bc34c4007c1e29be3a',
    messagingSenderId: '375576181839',
    projectId: 'habittracker-443a8',
    storageBucket: 'habittracker-443a8.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgmYwVgTZMtsJDeSxdRbBwSkcdRusix8U',
    appId: '1:375576181839:ios:9431bc34c4007c1e29be3a',
    messagingSenderId: '375576181839',
    projectId: 'habittracker-443a8',
    storageBucket: 'habittracker-443a8.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8JVQFv0JCaarKX_kmiY5iZhL85mevj4E',
    appId: '1:375576181839:web:0ffa307eb95a4bc729be3a',
    messagingSenderId: '375576181839',
    projectId: 'habittracker-443a8',
    authDomain: 'habittracker-443a8.firebaseapp.com',
    storageBucket: 'habittracker-443a8.firebasestorage.app',
    measurementId: 'G-3HH6JM87QN',
  );
}
